from sqlalchemy import Column, String, DateTime, Text
from sqlalchemy.sql import func
from app.config.database import Base

class IdempotencyKey(Base):
    __tablename__ = "idempotency_keys"
    __table_args__ = {'extend_existing': True}

    key = Column(String(50), primary_key=True) # UUID generated by React
    response_body = Column(Text, nullable=False) # Stores the successful JSON response
    created_at = Column(DateTime(timezone=True), server_default=func.now())